name: 🚀 Marktguru PR workflow

on:
  pull_request:
    types: [opened, reopened, closed]  # Trigger on PR creation, reopening, and closing
  
  pull_request_review:
    types: [submitted]  # Trigger when a review is submitted

permissions:
  pull-requests: write  # Allow workflow to approve PRs and add labels
  contents: write


jobs:
  add-label:
    runs-on: ubuntu-latest
    if: contains(fromJSON('["opened", "reopened", "synchronize"]'), github.event.action)
    outputs:
      pr_label: ${{ steps.set-label.outputs.pr_label }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      
      - name: Add label based on branch name
        id: set-label
        run: |
          # Extract the branch name (e.g., feature/mr/1234 -> 1234)
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          FEATURE_NUMBER=$(echo "$BRANCH_NAME" | awk -F'/' '{print $NF}')
          PR_LABEL="feature-${FEATURE_NUMBER}"

          # Check if the label exists
          LABEL_EXISTS=$(gh label list --json name -q ".[] | select(.name == \"$PR_LABEL\")")

          if [ -z "$LABEL_EXISTS" ]; then
            # If the label doesn't exist, create it
            RANDOM_COLOR=$(printf "#%02x%02x%02x" $((RANDOM % 256)) $((RANDOM % 256)) $((RANDOM % 256)))

            echo "Label '$PR_LABEL' does not exist. Creating it now."
            gh label create "$PR_LABEL" --color "$RANDOM_COLOR" --description "Feature branch label: $PR_LABEL"
          else
            echo "Label '$PR_LABEL' already exists."
          fi
          
          gh pr edit ${{ github.event.pull_request.number }} --add-label "$PR_LABEL"
          echo "pr_label=$PR_LABEL" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  auto-approve:
    runs-on: ubuntu-latest
    needs: add-label
    if: github.event.pull_request.base.ref == 'test' && contains(fromJSON('["opened", "reopened", "synchronize"]'), github.event.action)
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get PR Label and Author
        id: pr_info
        run: |
          TEST_PR_TITLE="${{ github.event.pull_request.title }}"
          TEST_PR_AUTHOR="${{ github.event.pull_request.user.login }}"
          TEST_PR_NUMBER="${{ github.event.pull_request.number }}"
          CURRENT_USER="${{ github.actor }}"

          echo "PR label: ${{ needs.add-label.outputs.pr_label }}"
          echo "Test PR title: $TEST_PR_TITLE"
          echo "Test PR author: $TEST_PR_AUTHOR"
          echo "Test PR number: $TEST_PR_NUMBER"
          echo "Current user: $CURRENT_USER"

          echo "test_pr_number=$TEST_PR_NUMBER" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Check for matching closed PR in integration
        id: check-pr
        run: |
          PR_LABEL="${{ needs.add-label.outputs.pr_label }}"
          echo "Checking for closed PR with the label: '$PR_LABEL' on integration"

          # Fetch closed PR matching the label
          INTEGRATION_PRS=$(gh pr list --repo ${{ github.repository }} --base integration --state closed --json labels,number,mergedAt --jq \
            '[.[] | select(.labels[].name=="'"$PR_LABEL"'")] | sort_by(.mergedAt)')

          PR_COUNT=$(echo "$INTEGRATION_PRS" | jq 'length')

          echo "Number of closed PRs with label '$PR_LABEL': $PR_COUNT"

          if [[ "$PR_COUNT" -eq 0 ]]; then
            echo "No closed PR found in integration with the label '$PR_LABEL'."
            echo "approve=false" >> $GITHUB_ENV
            exit 0
          fi
          
          # Extract all PR numbers and their merge commit SHAs
          MERGE_COMMITS=()
          for (( i=0; i<PR_COUNT; i++ )); do
            INT_PR_NUMBER=$(echo "$INTEGRATION_PRS" | jq -r ".[$i].number")
            MERGE_SHA=$(gh pr view $INT_PR_NUMBER --repo ${{ github.repository }} --json mergeCommit --jq '.mergeCommit.oid')

            echo "PR #$INT_PR_NUMBER - Merge Commit: $MERGE_SHA"
            
            INT_PR_REVIEWS=$(gh api repos/${{ github.repository }}/pulls/$INT_PR_NUMBER/reviews --jq '[.[] | select(.state=="APPROVED")] | length')

            if [[ "$INT_PR_REVIEWS" -eq 0 ]]; then
              echo "PR #$INT_PR_NUMBER was merged but was NOT approved!"
              echo "approve=false" >> $GITHUB_ENV
              exit 0
            fi
            echo "PR #$INT_PR_NUMBER was approved."
            MERGE_COMMITS+=("$MERGE_SHA")
          done
          echo "merge_commits=${MERGE_COMMITS[@]}" >> $GITHUB_ENV
          
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Compare changed files and checksums
        id: compare-files
        run: |
          # Get PR numbers
          TEST_PR_NUMBER=${{ env.test_pr_number }} # From previous step

          echo "Fetching changed files for PR #$TEST_PR_NUMBER (test) ..."
          TEST_FILES=$(gh pr view $TEST_PR_NUMBER --repo ${{ github.repository }} --json files --jq '.files[].path' | sort)

          echo "Files in test PR:"
          echo "$TEST_FILES"
    
          declare -A LATEST_FILE_COMMITS
          
          MATCH=true
          for MERGE_SHA in ${{ env.merge_commits }}; do
            echo "Checking files from merge commit: $MERGE_SHA"
            
            CHANGED_FILES=$(gh api repos/${{ github.repository }}/commits/$MERGE_SHA --jq '.files[] | {filename, status}')

            for FILE in $CHANGED_FILES; do
              LATEST_FILE_COMMITS["$FILE"]=$MERGE_SHA
            done
          done
          
          echo "${LATEST_FILE_COMMITS[*]}"
          
          if [[ "${#LATEST_FILE_COMMITS[@]}" -ne "$(echo "$TEST_FILES" | wc -l)" ]]; then
            echo "Mismatch in file count!"
            echo "Integration files (${#LATEST_FILE_COMMITS[@]}): ${!LATEST_FILE_COMMITS[@]}"
            echo "Test files ($(echo "$TEST_FILES" | wc -l)):"
            echo "$TEST_FILES"
            echo "approve=false" >> $GITHUB_ENV
            exit 0
          fi

          for FILE in "${!LATEST_FILE_COMMITS[@]}"; do
            LATEST_COMMIT=${LATEST_FILE_COMMITS["$FILE"]}
            FILE_NAME=$(echo "$FILE" | jq -r '.filename') 
            FILE_STATUS=$(echo "$FILE" | jq -r '.status')
            
            echo "Fetching latest version of $FILE_NAME from commit $LATEST_COMMIT..."

            if [[ "$FILE_STATUS" == "removed" ]]; then
                echo "File $FILE_NAME was removed on Integration. Just check the same on Test"
                TEST_CONTENT=$(gh api repos/${{ github.repository }}/contents/$FILE_NAME?ref=pull/$TEST_PR_NUMBER/head 2>/dev/null || echo "NOT_FOUND")
                if [[ "$TEST_CONTENT" == "NOT_FOUND" ]]; then
                    echo "File $FILE_NAME does not exist also in test PR. Skipping content check ..."
                    continue
                fi
                echo "File $FILE_NAME removed from Integration but exists on TEST PR! ..."
                echo "approve=false" >> $GITHUB_ENV
                exit 0
            fi


            # Get latest file content from integration commit
            INTEGRATION_CONTENT=$(gh api repos/${{ github.repository }}/contents/$FILE_NAME?ref=$LATEST_COMMIT --jq '.content')

            # Get file content from test PR branch
            TEST_CONTENT=$(gh api repos/${{ github.repository }}/contents/$FILE_NAME?ref=pull/$TEST_PR_NUMBER/head --jq '.content')

            # Compute SHA-256 hashes
            INTEGRATION_CHECKSUM=$(echo "$INTEGRATION_CONTENT" | sha256sum | awk '{print $1}')
            TEST_CHECKSUM=$(echo "$TEST_CONTENT" | sha256sum | awk '{print $1}')

            echo "Comparing file: $FILE_NAME"
            echo "Integration checksum: $INTEGRATION_CHECKSUM"
            echo "Test checksum: $TEST_CHECKSUM"

            if [[ "$INTEGRATION_CHECKSUM" != "$TEST_CHECKSUM" ]]; then
              MATCH=false
              echo "Checksum mismatch in file: $FILE_NAME"
              break
            fi
          done
          
          
          if [[ "$MATCH" == "false" ]]; then
            echo "File contents do not match (checksum mismatch)!"
            echo "approve=false" >> $GITHUB_ENV
            exit 0
          fi
          
          echo "All files match in content and checksum!"
          echo "approve=true" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto-approve if PR matches
        if: env.approve == 'true'
        run: |
          echo "Auto-approving PR as matching closed PR found in integration and it was approved."
          gh pr review ${{ github.event.pull_request.number }} --approve
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  assign-approver:
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved'  # Only trigger on approval
    steps:
      - name: Check Current Assignees
        id: check-assignees
        run: |
          echo "${{ github.event.review.state }}"
          
          APPROVER="${{ github.event.review.user.login }}"
          PR_NUMBER="${{ github.event.pull_request.number }}"
          
          echo "approver=$APPROVER" >> $GITHUB_ENV
          echo "pr_number=$PR_NUMBER" >> $GITHUB_ENV

          echo "Checking if $APPROVER is already assigned to PR #$PR_NUMBER"

          # Get the current assignees list
          CURRENT_ASSIGNEES=$(gh pr view "$PR_NUMBER" --repo ${{ github.repository }} --json assignees --jq '.assignees[].login')

          # Check if the approver is already assigned
          if echo "$CURRENT_ASSIGNEES" | grep -qw "$APPROVER"; then
            echo "$APPROVER is already assigned. Skipping assignment."
            echo "assign=false" >> $GITHUB_ENV
          else
            echo "$APPROVER is not assigned. Assigning now."
            echo "assign=true" >> $GITHUB_ENV
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Approver as an Assignee to PR
        if: env.assign == 'true'
        run: |
          echo "Assigning ${{ env.approver }} to PR ${{ env.pr_number }}"

          gh pr edit "${{ env.pr_number }}" --repo ${{ github.repository }} --add-assignee "${{ env.approver }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  delete-feature-branch:
    runs-on: ubuntu-latest
    if: github.event.action == 'closed' && github.event.pull_request.merged == true && contains(fromJSON('["main", "master"]'), github.event.pull_request.base.ref)
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      
      - name: Delete feature branch if PR is approved and merged to main
        run: |
          git fetch --prune
          git push origin --delete ${{ github.event.pull_request.head.ref }}
          
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  delete-temp-branch:
    runs-on: ubuntu-latest
    if: github.event.action == 'closed' && github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'temp/')
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      
      - name: Delete temporary branch if PR is approved and merged
        run: |
          echo "Action: ${{ github.event.action }}"
          echo "Merged: ${{ github.event.pull_request.merged }}"
          echo "Ref: ${{ github.event.pull_request.head.ref }}"
          git fetch --prune
          git push origin --delete ${{ github.event.pull_request.head.ref }}
              
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        